[workspace]
resolver = "2"
members = [
    "crates/lm-abi",
    "crates/lm-source",
    "crates/lm-types",
    "crates/lm-hir",
    "crates/lm-bytecode",
    "crates/lm-verify",
    "crates/lm-value",
    "crates/lm-vm",
    "crates/lm-compiler",
    "crates/lm-cli",
    "crates/lm-host",
    "crates/lm-testkit",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
