[package]
name = "lm-vm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lm-abi = { path = "../lm-abi" }
lm-bytecode = { path = "../lm-bytecode" }
lm-digest = { path = "../lm-digest" }
lm-graph = { path = "../lm-graph" }
lm-heap = { path = "../lm-heap" }
lm-jit = { path = "../lm-jit" }
lm-link = { path = "../lm-link" }
lm-math = { path = "../lm-math" }
lm-regex = { path = "../lm-regex" }
lm-verify = { path = "../lm-verify" }
lm-value = { path = "../lm-value" }
