[package]
name = "lm-jit"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cranelift-codegen = "=0.129.2"
cranelift-frontend = "=0.129.2"
cranelift-jit = "=0.129.2"
cranelift-module = "=0.129.2"
cranelift-native = "=0.129.2"
lm-abi = { path = "../lm-abi" }
lm-bytecode = { path = "../lm-bytecode" }
lm-value = { path = "../lm-value" }
lm-verify = { path = "../lm-verify" }
